spring:
  application:
    name: ecommercexyz

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000
      ttl: 3000

ecommerce:
  db:
    user-pk-prefix: "USER#"
    profile-sk: "PROFILE"
    order-prefix: "ORDER#"
    item-type: "ITEM"
    order-details-sk: "DETAILS"

  service:
    history-order-limit: 10

aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost:8000}
  region: ${AWS_REGION:us-east-1}
  accessKey: ${AWS_ACCESS_KEY_ID:dummy}
  secretKey: ${AWS_SECRET_ACCESS_KEY:dummy}

server:
  port: 8080

logging:
  level:
    software.amazon.awssdk: WARN
    com.unimag: DEBUG